### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#126]
Logged in users navigating to qri.cloud will see their dashboard.  Anonymous users will see a landing page:

We have decided to keep the landing page of qri.cloud minimal, and use qri.io as the main place for attracting new users and explaining what we do.

To that end, let's design the landing page of qri.cloud to be a two column layout, on the left will be some welcome info and perhaps a search input, on the right will be the login/signup form (but not in a modal).

**Comment by chriswhong** [comment]
An example: 
![image](https://user-images.githubusercontent.com/1833820/132704015-838680e5-6553-4430-a5c0-bfde48b7c553.png)

**Comment by tefyzambrano** [comment]
https://user-images.githubusercontent.com/85688198/137350303-856d56a5-0bea-4017-92e2-a728950487fc.mov

**Comment by b5** [comment]
closed by #451
