### ISSUE TITLE
HTTPS Websocket Error 

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#160]
Observed on rosebud.qri.cloud after attempting to log in

<img width="1061" alt="Home___Qri_Cloud" src="https://user-images.githubusercontent.com/1833820/119351714-c86dde00-bc6e-11eb-876b-35e1c845949c.png">

**Comment by Arqu** [comment]
This was a bad config update on my end while working with the ops stuff. Should be fixed now.
Thx for the catch.
