### ISSUE TITLE
Workflow Cell Outputs sometimes don't show up

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#210]
We seem to have lost the green output box when using ‘print()’ in a cell.  Got it to reappear, but it’s spotty.  Seeing some instances where dry run gives everything checks but doesn’t show output at all.  Not sure how to reproduce, it’s erratic.  This will need some investigation

I think we are not resetting the state of each step then a dry run is triggered.  If it fails they still show checkboxes and the output is not shown.

**Comment by chriswhong** [comment]
Need to confirm whether this is still happening, haven't seen it in a while

**Comment by ramfox** [comment]
@chriswhong I can vouch for also not having seen this when working with cloud. Can we close this?

**Comment by chriswhong** [comment]
Closing, haven't seen this in a while
