### ISSUE TITLE
Info items in DatasetHeader are still showing dummy data

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#217]
Need `stats` in the `/get` response, qri core issue: https://github.com/qri-io/qri/issues/1823

**Comment by ramfox** [comment]
We will be adding a `/collection/get` endpoint, that takes a `Ref` or `InitID`, and returns a `VersionInfo` with the additional fields needed to populate the `DatasetHeader`

Check out this comment for more details: https://github.com/qri-io/qri/issues/1880#issuecomment-910422967
