### ISSUE TITLE
App explodes on missing structure

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#219]
Not clear how to reproduce, @Arqu can elaborate

**Comment by Arqu** [comment]
Sorry for the weird notes should have added more detail.

Anyways, this is not specific to just structure, but pretty much whenever we get a response that is not in line with what was expected. Ie cloud and core returned the search response in a differently shaped response object and that just killed the UI for me. We should have better error handling overall when mishaps like this happen. User loses a connection or something similar and can have a bad experience.

**Comment by chriswhong** [comment]
Closing as I believe the most obvious instances of this have been addressed.
