### ISSUE TITLE
DatasetHeader stats (needs new backend endpoint)

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#259]
We do not have an endpoint to provide the stats in the dataset header (followers, download count, etc).  Some changes are discussed here https://github.com/qri-io/qri/issues/1880

**Comment by ramfox** [comment]
We will be adding a `/collection/get` endpoint, that takes a `Ref` or `InitID`, and returns a `VersionInfo` with the additional fields needed to populate the `DatasetHeader`

Check out this comment for more details: https://github.com/qri-io/qri/issues/1880#issuecomment-910422967

**Comment by chriswhong** [comment]
Based on conversation at today's standup:
-  Hide follower count in dataset header
- Download count *should* start working properly, so we need to follow up to make sure that data is flowing through to the fontend.

**Comment by Arqu** [comment]
Done as described in https://github.com/qri-io/cloud/pull/579
There's another issue for the more general case for this.
