### ISSUE TITLE
User can deploy a workflow without running it now

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#262]
We have UI for "Run now" on deploy, but it is ignored by the backend at the moment.

**Comment by chriswhong** [comment]
Relevant, I lost code on a long-running deploy that may have failed.  I think deploy should just result in a commit with the updated `transform`.  If Run Now is selected, that deploy modal should close as successful and then the user should see a toast for the run and be able to see the logging from the run as it is happening.

**Comment by b5** [comment]
This is blocked until we can save datasets without a body component. blocked on qri-io/qri#1908
