### ISSUE TITLE
User can inspect individual run logs

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#265]
Users need to inspect runs and see a console-style output to see what happened and when.  Each row in the run log can be expanded, revealing a scrollable terminal window.

**Comment by boandriy** [comment]
hey @Arqu , I think I will need your input here. Not sure if there is currently a way to get this extended run log terminal window. Here is how it looks in design: 
![image](https://user-images.githubusercontent.com/22635911/140892605-8cf52d11-b7d3-44eb-8291-04059a53d643.png)

**Comment by Arqu** [comment]
Hmm, not really sure what's supposed to be in the run log content wise. The things in that screenshot are just a mock screenshot of some script. 

Is it to be the run output that we show under the code cells in the workflow editor when doing dry runs? @ramfox Do we even persist these with runs at all?

**Comment by chriswhong** [comment]
User story: I got an email from Qri that my run failed, and I need to go see what happened.  I go to the Run Log, find the failure in question, and expand it.  I can see the error that caused the problem.  I then click back to the workflow editor, modify the code, dry run it to confirm that I fixed the bug, and redeploy the workflow.

Another user story:  I click run now from the run log.  I see what looks like a terminal open up, and can watch in real-time as Qri queues my run, starts my run, and completes it.  

I think this output should be a combination of Qri logging various steps: 
`2021-11-06T12:30:00 Workflow Queued, waiting for resources...`
`2021-11-06T12:31:00 Workflow Started`
`2021-11-06T12:31:00 Workflow Complete, no changes to dataset`
etc.

It can also include anything that was logged with `print()` in the transform script.

I've also thought that certain types of code (such as HTTP requests, commits, etc) should have their own default output:
`2021-11-06T12:31:00 HTTP GET request to https://foo.bar...`
`2021-11-06T12:31:00 Response 200 OK, transferred 1.2KB`

**Comment by Arqu** [comment]
Ok, I follow the usage pattern here. We don't really have the infrastructure codewise to support this yet. Ie those events are not persisted + we are missing things like tracking those http requests (that's relying a lot on Dustins starlark and flow analysis work). 

It's not an insignificant chunk of work. Let's bump up a discussion on this and see when/how we tackle this.

**Comment by Arqu** [comment]
@chriswhong @boandriy  run logs are now merged. You can get them by hitting `POST /auto/runinfo` with body `{"id":"123-run-id-456"}`
