### ISSUE TITLE
Rendering a Preview requires multiple API calls

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#266]
`/ds/get` should include a body with 100 rows.  Right now we have to make multiple calls to render the dataset preview.

**Comment by b5** [comment]
hmmm... this might be the result of cloud not using the `dataset/preview` pacakge, which definitely does inline 100 rows of the body in a preview: https://github.com/qri-io/dataset/blob/master/preview/preview.go

@ramfox I'd love it if you could investigate on the cloud side
