### ISSUE TITLE
Workflow API call errors when logged out

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#277]
Go to http://localhost:3000/ds/chriswhong/brooklyn_hourly_temperature_humidity/workflow when not logged in, the transform script does not appear on the page

While we are at it:
- [x] Disable Deploy button on existing workflow when not logged in

**Comment by ramfox** [comment]
looks like the first part of this issue has been resolved #439 fixes the deploy enabled/disabled issue
