### ISSUE TITLE
User can see information about the latest run in collection 

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#285]
The latest run for an automated dataset should appear in the "latest run" column in the Collection

**Comment by ramfox** [comment]
- [ ] backend needs to track the "run start time" in the `Collection` qri-io/qri#1944
- [x] add `runTime` field to `VersionInfo`
- [x] in `CollectionTable` component, the hard-coded `23` should be replaced by `versionInfo.runCount`
- [x] in `CollectionTable` component, the time should be changed from the `versionInfo.commitTime` to `versionInfo.runTime` + `versionInfo.duration`
- [x] in `selectCollection`, remove references to `API_RUNNING` & `state.collection.running`
- [x] instead, pull `running` using new `selectRunning` selector
- [x] adjust `CollectionState` to update collection if we get events that indicate that a workflow is running, much like the collection in core updates.
- [x] in `CollectionTable`, if `run.status === "running"` show the spin wheel, make the run count `-` and the time `-`
