### ISSUE TITLE
Remove not working

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#287]
Observed when using rosebud-api.qri.cloud

**Comment by ramfox** [comment]
have confirmed that this is not a local issue

`https://rosebud-api.qri.cloud/ds/remove` w/ params `{ ref: "qri_test_ramfox/test_status"}` fails with a 404 error

**Comment by b5** [comment]
@Arqu would love to loop you in on this one.

**Comment by Arqu** [comment]
Hmmm, so the reason this is erroring out is that the route is not added to cloud yet.
Now there is some thought that has to go into it:
- If I just pipe it into core, we will be physically deleting full datasets from cloud, along with logs, versions etc. I'm not really happy with that as it's pretty destructive and a small slip could be very dangerous later
- We can do a "cloud" version of the endpoint where we simply soft delete all the datasets and let that be it. This has 2 issues: we're keeping stuff around that should be gone and versions might start to collide later as we don't yet support really branched logbook writes. (this would be more like "unpublish" than "remove")

I'm still for option 2 but want to get a pulse check on this and how that flows into the private data conversations.
