### ISSUE TITLE
Implement end to end testing

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#294]
Let's add an end to end test suite.  To start, let's focus on the following golden path:

- New User Signs Up & Logs In
- From Collection View, click New Dataset
- Add a script that will produce a body, metadata, etc
- Dry Run, check that runstatus for each step is updated appropriately
- Add a cron trigger
- Deploy the workflow (and add a name in the modal)
- UI should navigate to preview route for the new dataset
- View History, there should be a newly created commit
- Inspect the various components and confirm they are rendered as expected
- Go back to workflow
- Confirm that the cron trigger matches what was configured in earlier steps
- Make a change to the script that will result in a new version
- Deploy the changes
- UI should navigate to preview route
- View History, there should be a newly created commit
- Inspect the various components and confirm they are rendered as expected

Implementation Details:

**Comment by b5** [comment]
I've been looking through different e2e testing frameworks, and so far I think [playwright](https://playwright.dev) is the way to go

**Comment by chriswhong** [comment]
Closed by #311
