### ISSUE TITLE
Route Refactoring

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#297]
Refactor routes to match existing qri cloud

`/preview` ->  `/` 

History should show `/nyc-transit-data/turnstile_daily_counts_2019/history#body`
or `https://rosebud.qri.cloud/nyc-transit-data/turnstile_daily_counts_2019/at/ipfs/QM.../history#body`

No changes to `/workflow`

`/history`-> `/runs`

**Comment by boandriy** [comment]
Hey @chriswhong , can you tell me why we need the #body at the end of history route? is that just naming convention?
