### ISSUE TITLE
Pagination on ds/get body not working

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#299]
`https://rosebud-api.qri.cloud/ds/get/chriswhong/every-ten-minutes/at/ipfs/QmaaTYHwjSoHFMsAyay969CJSKDWYYqnLjaf5fdFpw9DUx/body?page=10&pageSize=10`

It looks like the backend is ignoring the `page` and `pageSize` query params and returning the full body

**Comment by Arqu** [comment]
Got a PR up, but in short, `limit` & `offset` are the paging params on this endpoint, I've added `page` & `pageSize` in that PR. Will bump cloud too once this is in.
