### ISSUE TITLE
Workflow Cell output is cleared after editing code

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#313]
This is likely being cleared when we calculate `isDirty` for the workflow, but we should leave it around as it is helpful in debugging.

My story:  I am trying to transform several columns in each row of the dataset, and am using `print()` to log my work.  I need to identify the columns so I can pull items out of a list, but when I start writing code, the output disappears and I need to dry run again to find the next column and continue writing code.

**Comment by boandriy** [comment]
Hey, @b5 , @ramfox , the reason why the output is cleared is that on cell script edit we call `changeWorkflowTransformStep`: 
```typescript
function changeWorkflowTransformStep(state: WorkflowState, action: SetWorkflowStepAction) {
  if (state.dataset.transform?.steps) {
    state.dataset.transform.steps[action.index].script = action.script
  }

  state.isDirty = calculateIsDirty(state)
  // clear out events after an edit to reset dry run RunStatus
  state.events = []

  return
}
```

Here we are clearing `state.events` - which leads to clear of cells outputs too.

The simplest way of solving this issue is just removing the line of code that clears the events state. But it will not only leave the output UI unchanged on edit, it will also leave the status of each step unchanged and dry run status unchanged.

The other way to solve this is - adding workflow state with output variable that would be an array of outputs. And using this new state variable to display the output to cells.

**Comment by ramfox** [comment]
@boandriy let's talk about this when I'm in on thursday, it relates to the issue I just filed about storing events in a different place in the state tree now that we are expecting automated runs to happen while we are editing a different workflow: #350 

But I think your instinct is right: we need a different way of storing and referring to events. We need to be able to keep the previous run & the current/next run.

But it would also be great to get some clarity around what the product team feels is the correct UI interaction.

@chriswhong, when you start editing the cell, do you expect all the previous run information to stay until you click "deploy" or "dry run" again (not only the cell output, but also the sidebar status and coloring around the cell), or do you expect the previous run information (everything besides the cell output) to be cleared when you go to edit the cell?

**Comment by chriswhong** [comment]
There has been some debate on this.  I think once you start editing, the success/failure state of a given block should be thrown out, and the rest should be retained until the next Dry Run.  This is what deepnote does and is worth emulating.

**Comment by chriswhong** [comment]
I think in addition to this, the "overall" state of the script should also reset, or maybe show some kind of "dirty" icon, as it's success/failure is also no longer valid once a cell has been edited.

**Comment by ramfox** [comment]
> or maybe show some kind of "dirty" icon, as it's success/failure is also no longer valid once a cell has been edited.

Is that something that needs to happen in this iteration? If so, is there a mock up avail?

**Comment by chriswhong** [comment]
I'd say yes, just use the gray circle with a line through it to show that the script is in a state where it can be dry run again. (Same icon we show before the dry run begins)

**Comment by boandriy** [comment]
Hey, After a discussion with @ramfox , this issue will be solved by introducing a new state variable to workflow state tree - areCellsEdited, which will be a boolean array  in which each item will represent if workflow cell was edited. In workflow outline and in workflow editor we will look into the array and if the cell was edited we will not show the output/status of the cell.
