### ISSUE TITLE
Free-form Workflow Editor

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#328]
This issue describes changes to the workflow editor UI that will go along with the new concept of "cells" for workflows.

Instead of named code blocks (setup, download, transform), the user can create an arbitrary number of code cells that will execute in order. 

- user can rearrange code cells
- user can add and remove code cells
- user can execute a single code cell

**Comment by chriswhong** [comment]
![image](https://user-images.githubusercontent.com/1833820/133824257-6c13cca0-fbd9-4776-8bba-3ece6f7fd1d9.png)

Consult the latest mockups on Figma.  The MVP for this feature will allow the user to:
- create new code cells (via button that appears between cells or button that is always present after the last cell)
- delete a cell
- rearrange cells (for now by using move up/move down buttons in a contextual cell menu)

While we are in here, we will also need to refactor the templates we had been using to pre-populate the workflow editor. See issue #335 for details

Other notes:
- The outline will remain, but will be simplified since cells are not named anymore.  It should just show (triggers, script, completion, and preview)
- Dry Run and Deploy are both header buttons

**Comment by b5** [comment]
closed by #338, #340, #343, and others
