### ISSUE TITLE
Re-think default code in workflow editor

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#335]
Concurrent with the free-form (cell-based) workflow editor refactor (#328) we should re-think the default code that is present when users start editing a new workflow.

In a past life, we had the user choose from a series of templates that perform different types of data loading.  We nixed that and the default (CSV download) has been present in the code cells when starting a new workflow, so that dry run will "work" immediately.

I think under the new setup where there are not named cells, we should just have plenty of well-commented starter code with the most commonly used things.  An experienced coder should be able to spend a couple of minutes looking through this starter code and get an idea of what they are working towards.  

Things to call out:
- This is Starlark, and is a lot like python
- We have dataframes, here's some basic methods
- This environment is for creating a new version of one and only one dataset.  You can pull from many sources, manipulate the data,  You are working towards a goal of calling dataset.commit() which will save a new version of this dataset.  This is ALWAYS the last step.

**Comment by b5** [comment]
closed by #340
