### ISSUE TITLE
Indicate that a code block is running

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#348]
Designs, forthcoming.  Running cells should be outlined in blue and/or include an output area beneath them showing the loading spinner in the same way we show a check/X for success/failure.

**Comment by tefyzambrano** [comment]
![Workflow_FullMenu_Script_Running](https://user-images.githubusercontent.com/85688198/135065199-9766d2bf-7ee5-4c4a-863b-7ab0d1d99733.png)
