### ISSUE TITLE
Show code block glyphs in outline

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#349]
Each code block should be represented by a glyph/row in the outline, where we can also show the block's status when Dry running the script.

We lost this functionality when we switched to free-form code cells because the cells no longer have names.  We can bring them back without names, the user will just be able to tell at a glance how many blocks there are and visualize the dry-run as it makes its way through the sequence

**Comment by tefyzambrano** [comment]
<img width="185" alt="Screenshot 2021-09-28 at 11 53 59" src="https://user-images.githubusercontent.com/85688198/135065397-e20651bb-ae3c-471e-a8a2-70eac8cccdd5.png">
<img width="185" alt="Screenshot 2021-09-28 at 11 53 52" src="https://user-images.githubusercontent.com/85688198/135065401-b984fbd7-75ba-459e-a232-c50d90433326.png">
<img width="194" alt="Screenshot 2021-09-28 at 11 53 43" src="https://user-images.githubusercontent.com/85688198/135065403-bee7b08c-a367-496a-8aa3-9e2674c706b4.png">
