### ISSUE TITLE
Schedule trigger Save button should be disabled if there were no changes

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#367]
![image](https://user-images.githubusercontent.com/1833820/136088699-cef1faae-b083-4c52-86f0-8a75fe55916f.png)

For new schedule triggers, save should always be enabled.
When editing an existing schedule trigger, Save should be disabled if there is no change to save.

**Comment by boandriy** [comment]
@chriswhong , we are updating the UI for adding/editing of triggers. So I am not sure this issue will still be relevant

**Comment by chriswhong** [comment]
Thanks for the reminder, I'll close this and revisit once the new UI is in place.
