### ISSUE TITLE
Workflow on dataset not owned by user should be read-only

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/frontend#368]
Users should have a read-only view on the workflow and/or a eventually a button that requests edit access, or at least a warning modal that they are trying to change the settings of a dataset they don't control. 

Right now users are able to tinker with the workflow settings of another user's dataset, however & fortunately, do not appear to be able to save those changes.

**Comment by chriswhong** [comment]
I think for now we just make sure the workflow editor is read-only for datasets the user doesn't own.

**Comment by tefyzambrano** [comment]
![Workflow_FullMenu_ViewOnly](https://user-images.githubusercontent.com/85688198/138424918-d66ff2d1-8d20-4417-af21-495e61dd83ff.png)
