### ISSUE TITLE
Commit list missing in history view

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#375]
![image](https://user-images.githubusercontent.com/1833820/136259756-962259c4-eccb-4339-8012-3914619363f2.png)

**Comment by ramfox** [comment]
This can be solved in qri core by adding an option for "filtering" from the `/activity` endpoint, which was always our long term plan when we combined the log & history routes into one.

**Comment by ramfox** [comment]
API:

Need to separate the fetches for history and for runs, & need two different places to put them in the state tree, & need to update the fetching locations to ensure we are pulling the correct data at the correct place.

Both fetches will be pulling from the same endpoint `/ds/activity`.

fetch history api request body:
```
...
body: {
  ref: ref,
  limit: limit,
  term: "history"
}
```

fetch run api request body:
```
...
body: {
  ref: ref,
  limit: limit,
  term: "run"
}
```
