### ISSUE TITLE
History View > Loading State and Transition between commits

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#382]
Instead of a spinner, the body shows "There's nothing here yet" until the body loads.  A spinner would be good, but maybe we can show a grayed out table.

**Comment by chriswhong** [comment]
![image](https://user-images.githubusercontent.com/1833820/137175733-200db70f-b2e9-421b-8b5f-c205f2d2d2fc.png)

The entire content area also "flashes" to this white box when navigating between commits.  Only the content should change, the layout with the commit info above and the component tabs should all stay in place.

The desired outcome is that the user can "surf" commit history, and not be interrupted by the loading state...  The layout should remain in place, and only the content areas should show loading states.

**Comment by tefyzambrano** [comment]
![HistoryView_FullMenu_NoChanges_LoadingState](https://user-images.githubusercontent.com/85688198/137901363-21f017aa-b0f0-4774-a11a-4eb1d8f92f6a.png)

**Comment by boandriy** [comment]
@tefyzambrano , it is possible without header.
