### ISSUE TITLE
Need a consistent way to know whether a version was created from a workflow/transform

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#430]
![image](https://user-images.githubusercontent.com/1833820/137510593-40dc3246-e835-4372-a6e2-08264981d08f.png)

The list on the left is able to use the existence of `runID` in dataset activity to show the automation icon (this is also used in the collection view and activity list).

However, the `CommitSummaryHeader` is derived from the full `dataset` used to render this version, and that does not include `runID` or anything else we can use to show the same icon.

This is inconsistent.  Wherever we show information about a version, we need to be able to show whether that commit was created by a transform vs manual.

**Comment by chriswhong** [comment]
Update:  We have added an `automated` (boolean) prop to `DatasetCommitInfo` which is used to show the automation icon and indicate the commit was machine-made.

The only places we can't show this because we don't have enough information are:
- Above the tabs in the history view
- On Dataset Previews

In all other places we can use `runID` or just show it all the time (e.g. all commits shown in run log are automated)

**Comment by ramfox** [comment]
We do have a `runID` field on the commit! Just need to surface it on frontend.
