### ISSUE TITLE
refactor(workflow): only logged-in users should be able to "dry run" a workflow

### ISSUE THREAD

**Issue by ramfox** [qri-io/frontend#441]
Like the `Deploy` button, a user that is not logged in should be prompted to login or create and account before being allowed to dry run the transform.

**Comment by chriswhong** [comment]
I think we need to clarify the desired behavior here.  Dry run should only be an option for the dataset owner.  Anonymous users or logged-in users who do not own the dataset should see the disabled dry run button.  

The text in the tooltip should say "Only the dataset's owner can dry run".  Later we can add "forking" or "cloning" so other users can quickly replicate and try whatever public code they find in workflows.
