### ISSUE TITLE
Punchlist

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#448]
This is an issue for minor updates or text changes:

- [x] Fix Horizontal scroll on splash page (it should not have horizontal scroll unless width < 1080px

- [x] Workflow: New Version Preview and completion hooks are wider than code cells.

- [x] Text in block button is not vertically centered
![image](https://user-images.githubusercontent.com/1833820/139273812-e928b874-4248-461d-a743-37c9ea831267.png)

- [x] Body font size too small
![image](https://user-images.githubusercontent.com/1833820/139327318-abf7452c-dd3f-4f67-8b9e-f8242771a4cf.png)

- [x] Add tooltips on all download buttons, use browser  `title` attribute (make sure it's clear what the user will download)

- [x] Get rid of "There's nothing here yet" loading placeholder for bodies.  Show the body loading state instead

- [x] Chrome suggestions in search input shows a highlighted area. This should fill the entire input (adjust padding ) 

![image](https://user-images.githubusercontent.com/1833820/139331062-0880afb1-3245-4ee3-bf2f-5ad791ade007.png)

I did this on qri.io already, so may be copy-pastable: 
![image](https://user-images.githubusercontent.com/1833820/139439641-f3f71669-e1e7-45b6-be32-9cb1ab72b868.png)

- [x] Update favicon

**Comment by tefyzambrano** [comment]
Workflow Page

- [x] Side menu should be center to the title and icon of "Dataset Menu"
<img width="144" alt="Screenshot 2021-10-26 at 10 25 12" src="https://user-images.githubusercontent.com/85688198/138840558-5a043f75-dd7f-4dba-ac12-7f929daa127f.png">

- [x] The "+Code" button in between the Code Blocks, should have the same width of those code blocks
<img width="1110" alt="Screenshot 2021-10-26 at 10 38 31" src="https://user-images.githubusercontent.com/85688198/138842649-e61b5944-4c9e-4ccd-b6e2-3cbaee0aa748.png">
 
- [ ] I haven’t deploy or dry run the Script and I see that we have a green line after printing, that should be gray not green
<img width="864" alt="Screenshot 2021-10-26 at 10 42 18" src="https://user-images.githubusercontent.com/85688198/138843332-af80b239-08e3-4566-bd68-84adea223161.png">

- [x] Between the tabs on Next preview version and the white box there's a space of a pixel or so and that shouldn’t be there
<img width="511" alt="Screenshot 2021-10-26 at 10 46 49" src="https://user-images.githubusercontent.com/85688198/138843908-ecfe6e8f-433b-4ad9-9da9-cac25f08a698.png">

- [x] "On Completion" title is gray and should be black
<img width="537" alt="Screenshot 2021-10-26 at 10 49 55" src="https://user-images.githubusercontent.com/85688198/138844337-eb6436eb-8030-4f57-8715-01a49715a42c.png">

- [x] The top corners are more curved that the bottom ones, all of them should be the same as the bottom ones
<img width="887" alt="Screenshot 2021-10-26 at 10 54 26" src="https://user-images.githubusercontent.com/85688198/138845262-1b804aee-026d-4141-80ab-f35cfcf663ba.png">

- [ ] When you Dry Run and have something printing on the bottom and you click on that box to make an action, the border/outline of the box should be thick all around and it's just happening on the sides not on the top and the bottom
<img width="872" alt="Screenshot 2021-10-26 at 11 00 07" src="https://user-images.githubusercontent.com/85688198/138846662-1242eeee-d4b6-4042-8b20-f92ce8918df7.png">

- [x] The Dropdown should have a selective state, the outline should be highlighted pink when I click on it. Also the dropdown should be below the gray line and not on top.
<img width="329" alt="Screenshot 2021-10-26 at 11 08 04" src="https://user-images.githubusercontent.com/85688198/138847794-6435331b-8590-4392-af6e-5fe6902cbfca.png">

- [x] Should be highlighted in pink not blue
<img width="334" alt="Screenshot 2021-10-26 at 11 12 17" src="https://user-images.githubusercontent.com/85688198/138848125-0291c175-aee7-4a6c-a180-a1a11e142764.png">

- [x] The Download button on the History page should be filled not outline
<img width="953" alt="Screenshot 2021-10-26 at 12 04 30" src="https://user-images.githubusercontent.com/85688198/138857535-13a071bd-dba4-4069-99ca-069cebbdfe51.png">

**Comment by tefyzambrano** [comment]
- [x] These pinks are different, both of them should be the same color
<img width="267" alt="Screenshot 2021-10-26 at 12 11 05" src="https://user-images.githubusercontent.com/85688198/138858232-9228a165-3fb3-4c51-8249-b4aca2fbbec8.png">

**Comment by chriswhong** [comment]
- [ ] Data tab is active by default.  There is no preview, so all tabs should be disabled.
![image](https://user-images.githubusercontent.com/1833820/139516142-6263dd2f-4811-485a-bf14-e031166fb481.png)

**Comment by chriswhong** [comment]
![image](https://user-images.githubusercontent.com/1833820/139673099-312c122c-473e-41c7-9f0c-8b3baa3f363c.png)
- [ ] Two zeroes show during collection loading state
