### ISSUE TITLE
Password reset flow

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#458]
- [ ] Add `https://qri.cloud/signin/forgot` route with username or text input
- [ ] Ensure that the necessary endpoint exists
- [ ] Design email notification
- [ ] Set up email notification with template
- [ ] Confirm the entire flow from clicking "Forgot Password" in the sign up or login modals, receive email with link, click link, go to `signin/reset`, enter new password, see success message

**Comment by tefyzambrano** [comment]
This are the designs that are approved for reset password

![Reset-Password](https://user-images.githubusercontent.com/85688198/138717690-d8187d11-8542-4920-a237-11cd00ce03b2.png)
![Forgot-Password](https://user-images.githubusercontent.com/85688198/138717694-af2773fe-71ad-4823-8514-9773f04c2904.png)

**Comment by tefyzambrano** [comment]
If you are out of time and want to make something easier will be something like this:

![Reset-Password-NOW](https://user-images.githubusercontent.com/85688198/138717967-3d437a70-4f30-4f92-ad92-7ee6e24dda43.png)
![Forgot-Password-NOW](https://user-images.githubusercontent.com/85688198/138717971-4fcd6613-e3d9-4bae-ba19-56be24450451.png)
