### ISSUE TITLE
New Dataset Options

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#464]
When the user clicks "New Dataset", they should be presented with a couple of options:  Manual Upload or Create from Workflow

We need to present both of these options, and it feels like a modal with some helpful text, graphics, etc can help the user figure out what they want to do.

Even if we aren't ready to add manual upload just yet, we can add the option and disable it.

**Comment by tefyzambrano** [comment]
![NewDataset_Modal](https://user-images.githubusercontent.com/85688198/138728413-1190212d-f117-489d-b769-cdc05ed7453b.png)
