### ISSUE TITLE
[workflow]: Disable Completion Tasks

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#489]
Let's disable the completion tasks until they are functional.  We will need a design for the disabled state.
Let's also remove the "Push to Qri Cloud" option as it is confusing.

**Comment by tefyzambrano** [comment]
<img width="854" alt="Screenshot 2021-11-03 at 09 17 11" src="https://user-images.githubusercontent.com/85688198/140027806-ed1addc5-7079-41e8-888d-26fe602ee6ad.png">
