### ISSUE TITLE
Hover state for collection row links

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#511]
In Collection, clicking in the Name, Last Update, and Last Run column do different things, but the only highlight we have is place is to change the background color of the entire row.

We should indicate to the user that each of these will link to different things by highlighting them independently when hovered.  One idea is to just underline the text in each section on hover, or we could do more.  Need some design input.

**Comment by tefyzambrano** [comment]
https://user-images.githubusercontent.com/85688198/140381108-e81627a0-7cce-464c-a188-61c5d3ea98cb.mov
