### ISSUE TITLE
Last Run returned by /list shows "succeeded" when the run status should be "no changes"

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#512]

**Comment by Arqu** [comment]
@chriswhong do you have an example of this or is this just blanket on all of them?

**Comment by Arqu** [comment]
Same as #513 difference in accounting on cloud and core leads to the state not being recorded properly. A monkey patch has been issued which should hide this issue at the top level, but will not behave a 100% until a real fix is deployed.

**Comment by chriswhong** [comment]
Confirmed we are no longer observing this in the app
