### ISSUE TITLE
Incomplete Run Log returned from /activity with term: run

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#513]
Number of results does not match the totals returned from collection.  Unclear whether this is happening everywhere or just for existing datasets.

**Comment by Arqu** [comment]
Again I'll ask for some quick examples if you have them at hand.

**Comment by Arqu** [comment]
The issue is a big difference in run accounting on the cloud and core side. Needs some major surgery to get into the correct spot. A monkey patch is being added to fix some of the issues, but not all of it. We will continue to see some of this until it's fixed.

**Comment by Arqu** [comment]
This should be fixed now. LMK if you notice any quirks.
