### ISSUE TITLE
PunchList

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#534]
For small issues that don't warrant their own issue:

- [ ] [splash]: investigate missing background blobs on mobile safari
- [x] [footer]: Remove "Subscribe" from footer since there is no subscribe input
- [x] [toast]: The sub text on the toast when it’s successful, failed or running it is navy and should be black
- [x] [preview]: If there are no keywords, show "no keywords" in the metadata pane
- [x] [search]: remove `placeholder-opacity-50` in SearchBox

![image](https://user-images.githubusercontent.com/1833820/140339334-788a143f-5eb8-4120-b70c-6f9d55f5ae53.png)
- [x] Vertically center text in pagination buttons

![image](https://user-images.githubusercontent.com/1833820/140342915-c3333cb3-9e89-4102-98f1-925c0531db28.png)

- [x] Disable workflow in datasetnav for datasets that the user does not own.  Keep it in place with its tooltip, just disable it.

**Comment by boandriy** [comment]
[splash]: investigate missing background blobs on mobile safari - did some investigation here. For some reason the safari browser does not support the <filter> tag that is in out blob svg.
