### ISSUE TITLE
[auth]: User profile images missing

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#535]
Users should have been assigned a profile image.  We have no UI to change them, but the one we have assigned should show up in the app.  

![image](https://user-images.githubusercontent.com/1833820/140329855-e8c993d3-6b51-4c54-ad06-6668bf0eebb6.png)
![image](https://user-images.githubusercontent.com/1833820/140329863-daffcdea-8a3f-4f4b-b8b2-c7cd89d30b0b.png)

**Comment by ramfox** [comment]
closed by #564
