### ISSUE TITLE
[auth]: Redirect user on sign out

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#536]
When the user signs out, if they are on a private route (like collection) they should be redirected to the splash page.

If they are on a public route (dataset preview) they can stay on that route, but we need to make sure the UI changes to reflect that they are logged out (they should no longer be able to edit if they were viewing their own preview)

**Comment by ramfox** [comment]
current private routes:
`/collection`
`/dashboard`
`/activity`
`/notifications`
`/notification_settings`
`/username/dataset_name/workflow`
`/username/dataset_name/edit`
