### ISSUE TITLE
feat(*): add default `UserIcon` that generates an icon based on the user's initials and a qri color

### ISSUE THREAD

**Issue by ramfox** [qri-io/frontend#567]
If a user doesn't have a photo, generate an icon based on the username's first initial

colors here: https://www.figma.com/file/nKusm2LRrv5J1lcU5yKEtQ/Qrimatic-2.0-NEW?node-id=3263%3A35651

icon look here: https://www.figma.com/file/nKusm2LRrv5J1lcU5yKEtQ/Qrimatic-2.0-NEW?node-id=3418%3A89494

we can use a hash of the username to determine what color to show for the icon.

**Comment by chriswhong** [comment]
This was accomplished, we now choose from one of a few icons based on a hash of the username.
