### ISSUE TITLE
[History and Preview] Empty body

### ISSUE THREAD

**Issue by tefyzambrano** [qri-io/frontend#593]
When you are uploading a dataset and you deploy without running the body could be empty and the default state on the preview is loading dots.  This also happens on the history page.

What you should see is this

<img width="523" alt="Screenshot 2021-11-18 at 22 03 02" src="https://user-images.githubusercontent.com/85688198/142496324-7de0dc7d-4f0d-49ac-b8ef-c63ccfa17e7e.png">

**Comment by ramfox** [comment]
I can't find this in the figma board, next time we are on at the same time, can I follow you to find it? I need to get the svg of the face

**Comment by ramfox** [comment]
q for you @tefyzambrano 

For the Preview page, do you mean for it to show up like this:

<img width="1168" alt="Screen Shot 2021-11-26 at 12 38 18 PM" src="https://user-images.githubusercontent.com/17440142/143617710-a11c8277-06b8-4925-88c5-3088e4c59691.png">

or this:
<img width="1176" alt="Screen Shot 2021-11-26 at 12 58 52 PM" src="https://user-images.githubusercontent.com/17440142/143617736-66801580-3d26-4b63-b2d2-70271ce74ce0.png">

I can't find it in figma sorry!

**Comment by ramfox** [comment]
by the way, this is what it looks like on the history page:

<img width="1169" alt="Screen Shot 2021-11-26 at 1 01 11 PM" src="https://user-images.githubusercontent.com/17440142/143617850-271838ce-e49c-48a9-b0e0-a7329c9bd1dc.png">

**Comment by tefyzambrano** [comment]
Should be this:
> 
> <img alt="Screen Shot 2021-11-26 at 12 38 18 PM" width="1168" src="https://user-images.githubusercontent.com/17440142/143617710-a11c8277-06b8-4925-88c5-3088e4c59691.png">

**Comment by tefyzambrano** [comment]
> by the way, this is what it looks like on the history page:
> 
> <img alt="Screen Shot 2021-11-26 at 1 01 11 PM" width="1169" src="https://user-images.githubusercontent.com/17440142/143617850-271838ce-e49c-48a9-b0e0-a7329c9bd1dc.png">

This is perfect!
