### ISSUE TITLE
[Preview] Read Only state

### ISSUE THREAD

**Issue by tefyzambrano** [qri-io/frontend#597]
We don't have a way to show that you are seeing a read only dataset. It should look like this:

<img width="797" alt="Screenshot 2021-11-21 at 19 11 52" src="https://user-images.githubusercontent.com/85688198/142773927-7c8d5acd-4439-4660-99e2-a835a9e36a0c.png">

**Comment by chriswhong** [comment]
I am not sure this is necessary, I think the UI should speak for itself and let the user know they can or can't make changes. Let's discuss.

**Comment by chriswhong** [comment]
Most datasets are read only, and we recently added edit icons when a dataset can be edited.  Closing unless for now, we can re-open if users report confusion here.
