### ISSUE TITLE
[Profile] Log out state

### ISSUE THREAD

**Issue by tefyzambrano** [qri-io/frontend#605]
When I'm on the profile page and decide to log out, it stays on the same page. I think you should be send to the product landing page

<img width="1440" alt="Screenshot 2021-11-24 at 10 27 05" src="https://user-images.githubusercontent.com/85688198/143217267-cb13e362-704f-417f-bcab-dcb933ea6bee.png">
e.

**Comment by chriswhong** [comment]
Agree.  We already have redirects in place when the user tries to load a protected route, but I think it would be good UX to redirect to the landing page anytime a user manually logs out via the user menu.
