### ISSUE TITLE
feature suggestion: split code block here, disable and enable blocks

### ISSUE THREAD

**Issue by dustmop** [qri-io/frontend#625]
1. User places their cursor at some position in the code editor
2. They are able to split the code block right there
3. Code blocks could individually be disable or enabled with a click. Disabled blocks are entirely skipped over

This would make it much easier to work with the given example code, without fear of deleting useful reference code. It also provides a strong rational for why we support having multiple code blocks, rather than keeping everything in a single cell.

**Comment by chriswhong** [comment]
this doesn't follow after the automation UX refactor where we chose to go with one code block for now.  We can re-open for discussion if/when we decide to go with multiple code blocks again.
