### ISSUE TITLE
Modal Width Bug

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#632]
Recent work on modal minimum width has caused this layout on the deploy modal.  

![chriswhong_nyc-311-cb6-only_workflow_editor___Qri](https://user-images.githubusercontent.com/1833820/144889826-248ad431-ce20-478e-9692-ff20b493c14c.png)

**Comment by dustmop** [comment]
I observed the same issue with this other modal

<img width="403" alt="Screen Shot 2021-12-06 at 11 20 28 PM" src="https://user-images.githubusercontent.com/2515490/145048775-44830d02-944d-4934-a4e6-80b6a56619ee.png">
