### ISSUE TITLE
feat(`list`): updated list endpoint that includes workflowID

### ISSUE THREAD

**Issue by ramfox** [qri-io/frontend#96]
`qrimatic/list` endpoint & `qrimatic list` cmd

new data structure:
```
type WorkflowInfo struct {
  dsref.VersionInfo
  workflowID: string
}
```

Listing on `qrimatic` returns a `[]WorkflowInfo`

To compile this list:
  - needs to get list of workflows in reverse chronological order by activity, applying pagination
  - needs to get qri dataset endpoint in reverse chronological order by activity, applying pagination
  - the qri version info list will be a superset of the workflow list (one to one mapping of workflows to datasets, but there can be datasets without workflows)
  - zip up list, using the `VersionInfo` from the qri list, and the `workflowID` from the workflow list
  - return `WorkflowInfo[]`

Frontend should expect a list of `WorkflowInfo`s as a response from the `fetchWorkflows` action.
State tree should store a `WorkflowInfo[]`
The `Collection` component should take `WorkflowInfo[]` as a param

**Comment by chriswhong** [comment]
Closing, `/list` has been updated and provides workflowID if one exists.
